spring:
  application:
    name: media-service

  data:
    mongodb:
      database: media-service

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 20MB
